apiVersion: v1
kind: Service
metadata:
  name: citizen
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: citizen
  ports:
    - protocol: TCP
      port: 8443
      targetPort: http
