apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: tf-registry
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--noauth"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
        - name: mongodb-sidecar
          image: cvallance/mongo-k8s-sidecar:latest
          imagePullPolicy: IfNotPresent
          env:
            envFrom:
              configMapRef:
                name: mongodb-cfg
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: ""
      spec:
        accessModes: ["ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
